name: Deployment

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USER --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{env.DOCKER_USER}}/hackathon-ai-api:latest

      - name: Docker push
        run: docker push ${{env.DOCKER_USER}}/hackathon-ai-api:latest

      - name: Redeploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PWD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd hackathon/
            docker compose pull 
            docker compose up -d
            docker image prune -f
